<?php

/*****************************************************
* modules/uenv/loc/module.en.php
* module english locale file
*(c)virt2real.de 2014
* draft, by keios
/*****************************************************/

$lang = array(// common items
              'M_DESC'               => 'uEnv',
              // module-specific
              'M_ERR_NO_ACCESS'      => 'cannot access file',
              'M_ERR_NO_WRITE'       => 'can not write to',
              'M_SAVE_SUCCESS'       => 'settings saved',
              'M_ERR_NO_EDIT_UENV'   => 'Editing the parameters in uEnv.txt is only possible on booting from the SD card.',
              'M_NETWORK_INTERFACES' => 'Network interfaces',
              'M_WIFI'               => 'WiFi',
              'M_WIFI_MODULE'        => 'V2R WiFi module',
              'M_USB_WIFI'           => 'USB WiFi module',
              'M_WLAN_AP'            => 'WiFi AP',
              'M_LOCAL_NET'          => 'Local network',
              'M_LAN'                => 'LAN',
              'M_LAN1'                => 'LAN1 (EMAC)',
			  'M_LAN0MAC'			  => 'LAN0 MAC-address',
			  'M_LAN1MAC'			  => 'LAN1 MAC-address',
              'M_LEDS'               => 'LEDs',
              'M_BLUE'               => 'Blue',
              'M_GREEN'              => 'Green',
              'M_RED'                => 'Red',
              'M_HEARTBEAT'          => 'heartbeat',
              'M_MMC0'               => 'mmc0',
              'M_MMC1'               => 'mmc1',
              'M_CPU0'               => 'cpu0',
              'M_CONSOLE'            => 'Console',
              'M_DEVICE'             => 'Device',
              'M_PARAMETERS'         => 'Parameters',
              'M_KERNEL_OUTPUT'      => 'Kernel output',
              'M_PORTS'              => 'Ports',
              'M_SPI0'               => 'SPI0',
              'M_UART1'              => 'UART1',
              'M_1WIRE_PIN'          => '1-wire pin',
              'M_POWER_PIN'          => 'Power pin',
              'M_KERNEL'             => 'Kernel',
              'M_MEMORY'             => 'Memory',
              'M_CONTINUOUS_POOL'    => 'Continuous pool',
              'M_ROOT_DIRECTORY'     => 'Root directory',
              'M_BOOT_TIMEOUT'       => 'Boot timeout',
              'M_FS_TYPE'            => 'FS type',
              'M_OV2643'             => 'OV2643',
              'M_OV5642'             => 'OV5642',
              'M_OV5640'             => 'OV5640',
              'M_VIDEO_OUT'          => 'Video out',
              'M_COMPOSITE'          => 'Composite',
              'M_LCD'                => 'LCD',
              'M_VIDEO_MODE'         => 'Video mode',
              'M_PAL'                => 'PAL',
              'M_NTSC'               => 'NTSC',
              'M_OSD'                => 'OSD',
              'M_CAPTURE_INTERFACE'  => 'Capture interface',
              'M_IPIPE_MODE'         => 'IPIPE mode',
              'M_CONTSIZE_BUFFER'    => 'Buffer cont_bufsize',
              'M_CONTSIZE_BUFFER_2'  => 'Buffer cont2_bufsize',
              'M_BUFF_OFFSET'        => 'bufoffset',
              'M_WLAN_OVERRIDE'      => 'Wi-Fi settings override',
              'M_WLAN_SSID'          => 'Network name (SSID)',
              'M_WLAN_PASS'          => 'Network password',
              'M_WATCHDOG'	         => 'Watchdog',
			  'M_WDTTIMEOUT'		 => 'Timeout',
			  'M_GHID_TITLE'		 => 'HID emulation',
			  'M_GHID'		 		 => 'Emulate devices',
			  'M_HDMI'		 		 => 'HDMI',
			  'M_HDMI_VOFFSET' 		 => 'Vertical offset',
              );

?>
