<?php

/*****************************************************
* modules/uenv/loc/module.de.php
* module german locale file
*(c)virt2real.de 2014
* draft, by keios
/*****************************************************/

$lang = array(// common items
              'M_DESC'               => 'uEnv',
              // module-specific
              'M_ERR_NO_ACCESS'      => 'Kein Zugriff auf',
              'M_ERR_NO_WRITE'       => 'Kein Schreibzugriff auf',
              'M_SAVE_SUCCESS'       => 'Speichern erfolgreich',
              'M_ERR_NO_EDIT_UENV'   => 'Das Ändern der Bootparameter in uEnv.txt ist nur beim Booten von SD-Karte möglich.',
              'M_NETWORK_INTERFACES' => 'Netzwerkinterfaces',
              'M_WIFI'               => 'WLAN',
              'M_WIFI_MODULE'        => 'V2R WiFi-Modul',
              'M_USB_WIFI'           => 'USB WiFi-Modul',
              'M_WLAN_AP'            => 'WLAN Access Point',
              'M_LOCAL_NET'          => 'Lokales Netz',
              'M_LAN'                => 'LAN',
              'M_LAN1'                => 'LAN1 (EMAC)',
			  'M_LAN0MAC'			  => 'LAN0 MAC-address',
			  'M_LAN1MAC'			  => 'LAN1 MAC-address',
              'M_LEDS'               => 'LEDs',
              'M_BLUE'               => 'Blau',
              'M_GREEN'              => 'Grün',
              'M_RED'                => 'Rot',
              'M_HEARTBEAT'          => 'heartbeat',
              'M_MMC0'               => 'mmc0',
              'M_MMC1'               => 'mmc1',
              'M_CPU0'               => 'cpu0',
              'M_CONSOLE'            => 'Konsole',
              'M_DEVICE'             => 'Device',
              'M_PARAMETERS'         => 'Parameter',
              'M_KERNEL_OUTPUT'      => 'Kernelmitteilungen',
              'M_PORTS'              => 'Ports',
              'M_SPI0'               => 'SPI0',
              'M_UART1'              => 'UART1',
              'M_1WIRE_PIN'          => '1-Wire-Pin',
              'M_POWER_PIN'          => 'Strom-Pin',
              'M_KERNEL'             => 'Kernel',
              'M_MEMORY'             => 'Speicher',
              'M_CONTINUOUS_POOL'    => 'Continuous Pool',
              'M_ROOT_DIRECTORY'     => 'root-Verzeichnis',
              'M_BOOT_TIMEOUT'       => 'Boot Timeout',
              'M_FS_TYPE'            => 'Art des Dateisystems',
              'M_OV2643'             => 'OV2643',
              'M_OV5642'             => 'OV5642',
              'M_OV5640'             => 'OV5640',
              'M_VIDEO_OUT'          => 'Videoausgang',
              'M_COMPOSITE'          => 'Komposit',
              'M_LCD'                => 'LCD',
              'M_VIDEO_MODE'         => 'Videomodus',
              'M_PAL'                => 'PAL',
              'M_NTSC'               => 'NTSC',
              'M_OSD'                => 'On Screen Display',
              'M_CAPTURE_INTERFACE'  => 'Video Capture-Schnittstelle',
              'M_IPIPE_MODE'         => 'IPIPE-Modus',
              'M_CONTSIZE_BUFFER'    => 'Buffer cont_bufsize',
              'M_CONTSIZE_BUFFER_2'  => 'Buffer cont2_bufsize',
              'M_BUFF_OFFSET'        => 'bufoffset',
              'M_WLAN_OVERRIDE'      => 'Wi-Fi settings override',
              'M_WLAN_SSID'          => 'Network name (SSID)',
              'M_WLAN_PASS'          => 'Network password',
              'M_WATCHDOG'	         => 'Watchdog',
			  'M_WDTTIMEOUT'		 => 'Timeout',
			  'M_GHID_TITLE'		 => 'HID emulation',
			  'M_GHID'		 		 => 'Emulate devices',
			  'M_HDMI'		 		 => 'HDMI',
			  'M_HDMI_VOFFSET' 		 => 'Vertical offset',
              );

?>
